---
image: archlinux

packages:
  - pyenv
  - pyenv-virtualenv

sources:
  - https://git.sr.ht/~bow/crimson

tasks:
  - setup: |
      echo 'export PYENV_ROOT="${HOME}/.pyenv"' >> ~/.bashrc
      echo 'export PATH="${PYENV_ROOT}/bin:${PATH}"' >> ~/.bashrc
      echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
      echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
  - install: |
      source ~/.bashrc
      cd crimson
      make dev-pyenv
      make dev
  - lint: |
      source ~/.bashrc
      cd crimson
      make lint
  - test: |
      source ~/.bashrc
      cd crimson
      make test
