---
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  indentation:
    spaces: 2
    indent-sequences: yes
  key-duplicates: {}
  line-length:
    max: 120
  truthy: disable
